### Register a new user
POST http://127.0.0.1:8000/api/login
Authorization: Bearer 3|2qxNIIoePnUsxBvHNdVj26f5cAI9Cj0zlf1Natfib6e7b5f6
Content-Type: application/json

{
  "name": "abdlhadi",
  "email": "abdlhadi@example.com",
  "password": "123456"
}